behaviors:
  Pacman:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 512
      learning_rate: 0.0003
      beta: 0.001
      #beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 64
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
      gail:
        strength: 0.05
        gamma: 0.99
        encoding_size: 128
        demo_path: C:\Projects\Unity\Ziyuukenkyu2021\ml-agents\Project\Assets\Pacman\Demos\Pacman_0.demo
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 32
    summary_freq: 30000