behaviors:
  Pacman:
    trainer_type: sac
    hyperparameters:
      batch_size: 128
      buffer_size: 1000000
      learning_rate: 0.0003
      save_replay_buffer: true
      learning_rate_schedule: constant
      init_entcoef: 0.35
      buffer_init_steps: 0
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      #curiosity:
        #strength: 0.02
        #gamma: 0.99
     #gail:
        #strength: 0.05
        #gamma: 0.99
        #encoding_size: 128
        #demo_path: C:\Projects\Unity\Ziyuukenkyu2021\ml-agents\Project\Assets\Pacman\Demos\Pacman_0.demo
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 128
    summary_freq: 10000
    checkpoint_interval: 100000
        